import AdminAside from '@/components/admin-aside'
import AdminHeader from '@/components/headers/admin-header';
import { ThemeProvider } from '@/components/theme-provider';
import { Metadata } from 'next';
import "../globals.css";
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import React from 'react';
import AppProvider from '../AppProvider';
import RefreshToken from '@/components/refresh-token';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootAdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const cookieStore = cookies();
    const accessToken = cookieStore.get('accessToken');
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AppProvider
                        initialAccessToken={accessToken?.value}
                    >
                        <div className="flex h-screen">
                            <AdminAside />
                            <div className="flex flex-col flex-1 ml-64">
                                <AdminHeader />
                                <main className="flex-1 mt-16 p-4 overflow-y-auto">
                                    {children}
                                </main>
                            </div>
                        </div>
                        <RefreshToken />
                        <Toaster />
                    </AppProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
