import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "../context/AppProvider"; 
import { cookies } from "next/headers";
import RefreshToken from "@/components/refresh-token";
import UserHeader from "@/components/headers/user-header";
import TrailerModal from "@/components/trailer-modal";

const nunito = Nunito_Sans({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
	title: "My Cinema",
	description: "Generated by create next app",
};

export default function RootUserLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = cookies();
	const accessToken = cookieStore.get("accessToken");

	return (
		<html lang="en" suppressHydrationWarning>
			<body className={nunito.className}>
				<AppProvider initialAccessToken={accessToken?.value}>
					<UserHeader />
					{children}
					<RefreshToken />
					<Toaster />
					<TrailerModal />
				</AppProvider>
			</body>
		</html>
	);
}
